oauth2:
  user:
    google:
      client-id: 1065191115991-m252mqq4uu16kbeqohh96rv8h0be0o85.apps.googleusercontent.com
      client-secret: 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
      redirect-uri: http://localhost:8080/login/oauth2/code/google
  provider:
    google:
      token-uri: https://www.googleapis.com/oauth2/v4/token
      user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo

jwt:
  token:
    secret-key: secret_key